### ISSUE TITLE
определиться с фреймворком

### ISSUE THREAD

**Issue by geopr** [geopr/graphical-editor#6]
необходимо выбрать фреймворк для ui слоя (написать свой или вообще без него)

взять во внимание, что сложной работы с состоянием не планируется
нужно выбрать декларативный и минималистичный фреймворк, который позволит "открывать/закрывать панельки"

**Comment by VladislavPixel** [comment]
При выборе фреймфорка, мы с командой понимали, что требуется какое-то быстрое, легковесное и в то же время гибкое решение. Тащить виртуальную DOM в проект нам не хотелось. Выбор пал на Svelte. Это классное решение, которое всю свою основную работу делает не внутри браузера, а на этапе компиляции кода (при сборке). Также нам показалась удобной работа с реактивными переменными, которые доступны прям из разметки компонента. Svelte позволяет писать приложения меньшим количеством кода, так сказать обходиться "малой кровью". Выходной файл сборки намного меньше чем у популярных аналогов.
